name: Run Jest Unit Tests
on:
  push:
    branches-ignore:
      - "main"

jobs:
  run-jest-test-suite:
    runs-on: macos-15
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v4

      - name: ğŸ–¥ Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ’¬ Echo package.json version to Github ENV
        run: echo VERSION_NUMBER=$(node -p -e "require('./package.json').version") >> $GITHUB_ENV

      - name: ğŸ¤« Output TelemetryDeck JSON to TelemetryDeck          
        run: |
          echo "{" > telemetrydeck.json
          echo "\"appID\": \"${{ secrets.TELEMETRYDECK_APPID }}\"," >> telemetrydeck.json
          echo "\"clientUser\": \"anonymous\"," >> telemetrydeck.json
          echo "\"app\": \"Jellify\"" >> telemetrydeck.json
          echo "}" >> telemetrydeck.json

          
      - name: ğŸ¤« Output Glitchtip JSON to Glitchtip
        run: |
          echo "{" > glitchtip.json
          echo "\"dsn\": \"${{ secrets.GLITCHTIP_DSN }}\"" >> glitchtip.json
          echo "}" >> glitchtip.json
        
        
      - name: Output TelemetryDeck JSON
        run: |
          cat telemetrydeck.json
        
      - name: Output Glitchtip JSON
        run: |
          cat glitchtip.json
        
      - name: âœ… Validate TelemetryDeck JSON
        run: |
          node -e "JSON.parse(require('fs').readFileSync('telemetrydeck.json'))"

      - name: âœ… Validate Glitchtip JSON
        run: |
          node -e "JSON.parse(require('fs').readFileSync('glitchtip.json'))"

      - name: ğŸ Run yarn init-ios:new-arch
        run: yarn init-ios:new-arch
      
      - name: ğŸ” Run yarn tsc
        run: yarn tsc

      - name: ğŸ§ª Run yarn test
        run: yarn test

      - name: ğŸ¦‹ Check Styling 
        run: yarn format:check