name: Run Jest Unit Tests
on:
  push:
    branches-ignore:
      - "main"

jobs:
  run-jest-test-suite:
    runs-on: macos-15
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v4

      - name: ğŸ–¥ Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ’¬ Echo package.json version to Github ENV
        run: echo VERSION_NUMBER=$(node -p -e "require('./package.json').version") >> $GITHUB_ENV

      - name: ğŸ¤« Output TelemetryDeck JSON to TelemetryDeck          
        run: |
          echo "export const ENV = {" > telemetrydeck.js
          echo "  appID: '${{ secrets.TELEMETRYDECK_APPID }}'," >> telemetrydeck.js
          echo "  clientUser: 'anonymous'," >> telemetrydeck.js
          echo "  app: 'Jellify'," >> telemetrydeck.js
          echo "};" >> telemetrydeck.js

      - name: âœ… Validate TelemetryDeck JSON
        run: |
          node -e "JSON.parse(require('fs').readFileSync('telemetrydeck.js'))"

      - name: ğŸ¤« Output Glitchtip JSON to Glitchtip
        run: |
          echo "export const ENV = {" > glitchtip.js
          echo "  dsn: '${{ secrets.GLITCHTIP_DSN }}'," >> glitchtip.js
          echo "};" >> glitchtip.js

      - name: âœ… Validate Glitchtip JSON
        run: |
          node -e "JSON.parse(require('fs').readFileSync('glitchtip.js'))"

      - name: Output TelemetryDeck JSON
        run: |
          cat telemetrydeck.js

      - name: Output Glitchtip JSON
        run: |
          cat glitchtip.js

      - name: ğŸ Run yarn init-ios:new-arch
        run: yarn init-ios:new-arch
      
      - name: ğŸ” Run yarn tsc
        run: yarn tsc

      - name: ğŸ§ª Run yarn test
        run: yarn test

      - name: ğŸ¦‹ Check Styling 
        run: yarn format:check